// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2GEFyy8RjN2LqqqUCsSL0Eexi9klXuQU',
    appId: '1:172848621250:web:82ec41330d56b99e517d5b',
    messagingSenderId: '172848621250',
    projectId: 'carnova-b6118',
    authDomain: 'carnova-b6118.firebaseapp.com',
    storageBucket: 'carnova-b6118.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxYBtjms7pcUDPUDsGDBhGBZuk3CQsfZo',
    appId: '1:172848621250:android:72a2680b606f02bb517d5b',
    messagingSenderId: '172848621250',
    projectId: 'carnova-b6118',
    storageBucket: 'carnova-b6118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX-w0HtURqHjk_JAO8EYCSFmN1km0DWzI',
    appId: '1:172848621250:ios:e3590a4062ff4fd2517d5b',
    messagingSenderId: '172848621250',
    projectId: 'carnova-b6118',
    storageBucket: 'carnova-b6118.firebasestorage.app',
    iosBundleId: 'com.example.autoSwift',
  );
}
